In [ ]:
Numpy
Pandas
matplotlib
oenpyxl

In [ ]:
Understanding Numpy:

In [ ]:
How to setup and use it:

In [2]:
!pip install numpy

You are using pip version 9.0.1, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [5]:
!pip install --upgrade pip

Requirement already up-to-date: pip in c:\users\nagaraju\anaconda3.5\lib\site-packages (20.1.1)


In [6]:
!pip install numpy

In [8]:
!pip install numpy --upgrade 

Requirement already up-to-date: numpy in c:\users\nagaraju\anaconda3.5\lib\site-packages (1.18.5)


In [9]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\nagaraju\anaconda3.5\lib\site-packages (1.18.5)


In [16]:
array1=n.array([1,2,3,4,5])
array1

NameError: name 'n' is not defined

In [17]:
import numpy as n

In [18]:
array1=n.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [19]:
type(array1)

numpy.ndarray

In [20]:
numbers=[5,6,7,8,9]
array_two=n.array(numbers)
array_two

array([5, 6, 7, 8, 9])

In [21]:
array_of_zeros=n.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
array_of_zeros.shape

(3, 4)

In [23]:
array1.shape

(5,)

In [30]:
array_of_ones=n.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
array_of_fives=n.twos((3,3))
array_of_fives

AttributeError: module 'numpy' has no attribute 'twos'

In [33]:
array_of_ones=n.ones((1,4))
array_of_ones

array([[1., 1., 1., 1.]])

In [35]:
array_of_ones_int=n.ones((3,4),dtype=n.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [36]:
array_of_ones_int=n.ones((3,4),dtype=n.int)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])